keys:
  - &15turtle_igor age1nda42499l5x33lcw896zvlk0szfpsx6t8jdwgkckttvefx2cpduqzly5p6
  - &15turtle age1edh29afu25qh4qph0usphz360tewyw3n4z5jn5vqle29m4xl7umsf4my5c
  - &oak-1 age1usrwpke8edazf8ps3lnfd330xn6tnuhdx064lu2u73dxsmp2e3uswlc2l2
  - &coconut-2 age1umfmqwg48nlkkzn5tpemaffjl2cyvspt7kytzut35t2ckhz57dhs3a0qpk
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *15turtle_igor
        - *15turtle
        - *oak-1
        - *coconut-2
  - path_regex: hosts/coconut-2/secrets+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *15turtle_igor
        - *coconut-2