{ config, inputs, lib, pkgs, ... }:
let
  cfg = config.my.nps;
  inherit (lib) mkIf mkOption mkEnableOption mkForce mkDefault mkMerge types literalExpression;

  publicContainers = [
    "traefik"
    "homepage"
    "authelia"
    # "lldap" -- no longer publicly reachable; now served tailnet-only via a
    # dedicated host nginx vhost proxying to Traefik (see hosts/oak-1/default.nix).
    "paperless"
    "grafana"
    "pinepods"
    "alloy"
    "prometheus"
  ];
in {
  options.my.nps = {
    enable = mkEnableOption "Nix Podman Stacks (reverse proxy, auth, monitoring)";

    userName = mkOption {
      type = types.str;
      default = "deer";
      description = "User that runs the rootless Podman containers.";
    };

    hostIP4Address = mkOption {
      type = types.str;
      description = "IPv4 address used for explicit bindings (only relevant when Traefik is disabled).";
    };

    domain = mkOption {
      type = types.str;
      description = ''
        Base domain handled by Traefik. Build-time value.
        Read from a private, untracked file (e.g. /etc/nixos/nps-domain) by the
        host so the literal domain never lives in this repo.
      '';
    };

    acmeEmail = mkOption {
      type = types.str;
      description = "Let's Encrypt registration email. Cannot be loaded from a file (Traefik static config sources are mutually exclusive).";
    };

    defaultTz = mkOption {
      type = types.str;
      default = "America/Chicago";
    };

    storageBaseDir = mkOption {
      type = types.path;
      default = "/home/deer/stacks";
    };

    externalStorageBaseDir = mkOption {
      type = types.path;
      default = "/srv/array0/services";
    };

    mediaStorageBaseDir = mkOption {
      type = types.path;
      default = "/srv/array0/media";
    };

    cloudflared = {
      enable = mkEnableOption "systemd service running Cloudflare Tunnel with a token from sops";
      tokenFile = mkOption {
        type = types.path;
        description = "Dotenv file containing TUNNEL_TOKEN=... (for EnvironmentFile)";
      };
    };

    crowdsec = {
      bouncerKeyFile = mkOption {
        type = types.str;
        default = "${cfg.storageBaseDir}/crowdsec/bouncer-key";
        description = ''
          Persistent path to the Crowdsec LAPI key for the Traefik bouncer.
          The key is generated by a systemd oneshot on first activation and must
          live next to the Crowdsec LAPI database (Crowdsec registers the bouncer
          only once).
        '';
      };
    };

    secrets = {
      traefik = {
        cfDnsApiToken = mkOption {type = types.path;};
      };
      authelia = {
        jwtSecret = mkOption {type = types.path;};
        sessionSecret = mkOption {type = types.path;};
        storageEncryptionKey = mkOption {type = types.path;};
        # Gmail SMTP notifier credentials (replaces the default filesystem notifier)
        smtpUser = mkOption {type = types.path;};
        smtpPassword = mkOption {type = types.path;};
        oidc = {
          hmacSecret = mkOption {type = types.path;};
          jwksRsaKey = mkOption {type = types.path;};
        };
      };
      lldap = {
        adminPassword = mkOption {type = types.path;};
        jwtSecret = mkOption {type = types.path;};
        keySeed = mkOption {type = types.path;};
        # deerPassword = mkOption {type = types.path;};
      };
      homepage = {
        authSecret = mkOption {type = types.path;};
        oidcClientSecret = mkOption {type = types.path;};
      };
      paperless = {
        oidcClientSecret = mkOption {type = types.path;};
        secretKey = mkOption {type = types.path;};
        dbPassword = mkOption {type = types.path;};
        adminPassword = mkOption {type = types.path;};
      };
      monitoring = {
        grafanaOidcClientSecret = mkOption {type = types.path;};
      };
      pinepods = {
        adminPassword = mkOption {type = types.path;};
        dbPassword = mkOption {type = types.path;};
        oidcClientSecret = mkOption {type = types.path;};
      };
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      # NixOS-level prerequisites for rootless Podman
      boot.kernel.sysctl."net.ipv4.ip_unprivileged_port_start" = 0;
      virtualisation.podman.enable = mkDefault true;
      users.users.${cfg.userName}.linger = true;

      # Forward our flake inputs into the home-manager user submodule so that
      # `inputs.nix-podman-stacks.homeModules.nps` resolves there.
      home-manager.extraSpecialArgs.inputs = inputs;
    }

    # Wire the NPS home-manager module into the container user
    {
      home-manager.users.${cfg.userName} = {
        imports = [ inputs.nix-podman-stacks.homeModules.nps ];

        nps = {
          defaultTz = cfg.defaultTz;
          storageBaseDir = cfg.storageBaseDir;
          externalStorageBaseDir = cfg.externalStorageBaseDir;
          mediaStorageBaseDir = cfg.mediaStorageBaseDir;
          hostIP4Address = cfg.hostIP4Address;

          stacks = {
            docker-socket-proxy.enable = true;

            crowdsec = {
              enable = true;
            };

            traefik = {
              enable = true;
              domain = cfg.domain;
              # Cloudflare DNS challenge (merged into the traefik container's env)
              extraEnv.CF_DNS_API_TOKEN.fromFile = cfg.secrets.traefik.cfDnsApiToken;
              # Geoblock everything except the chosen country
              geoblock = {
                enable = true;
                allowedCountries = ["US"];
              };
              crowdsec = {
                enableLogCollection = true;
                middleware = {
                  enable = true;
                  bouncerKeyFile = cfg.crowdsec.bouncerKeyFile;
                };
              };
              # Custom LE email (build-time value, cannot come from a file)
              staticConfig.certificatesResolvers.letsencrypt.acme.email = mkForce cfg.acmeEmail;
              # Trust the cloudflared loopback origin so the real client IP in
              # X-Forwarded-For reaches the middleware plugins (geoblock,
              # crowdsec). Without this, Traefik rebuilds XFF from the loopback
              # connection and geoblock's allowPrivate makes it a no-op. Applies
              # to websecure-internal too (it mirrors websecure).
              staticConfig.entryPoints.websecure.forwardedHeaders.trustedIPs =
                mkForce [
                  "127.0.0.1/32"
                  "::1/128"
                ];
              staticConfig.entryPoints.websecure-internal.forwardedHeaders.trustedIPs =
                mkForce [
                  "127.0.0.1/32"
                  "::1/128"
                ];
              dynamicConfig.tls.options.default.sniStrict = mkForce false;
              # Allowlist used by lldap: RFC1918 LAN ranges plus Tailscale CGNAT
              # (IPv4 + IPv6), so the service is reachable from the LAN and the
              # tailnet but not from the public internet.
              #
              # ipAllowList must match on the X-Forwarded-For client IP rather
              # than the connection address: nginx proxies every request to
              # Traefik over the loopback socket bind, so the raw RemoteAddr is
              # always 127.0.0.1. depth=1 selects the rightmost XFF entry, which
              # nginx appends ($proxy_add_x_forwarded_for). Without ipStrategy
              # the middleware would reject everything regardless of source
              # (Traefik only shows the XFF-derived client in the access log).
              dynamicConfig.http.middlewares."ipwhitelist-tailnet".ipAllowList = {
                sourceRange = [
                  "10.0.0.0/8"
                  "172.16.0.0/12"
                  "192.168.0.0/16"
                  "100.64.0.0/10"
                  "fd7a:115c:a1e0::/48"
                ];
                ipStrategy.depth = 1;
              };
            };

            authelia = {
              enable = true;
              # 2FA everywhere: OIDC clients and the default access-control policy
              defaultAllowPolicy = "two_factor";
              # Brand the TOTP enrollment (shown by authenticator apps)
              settings.totp.issuer = cfg.domain;
              # Deliver identity-validation codes by email instead of writing them
              # to the filesystem notifier. Gmail rewrites the From header to the
              # authenticated account, so sender/username come from the sops secret
              # (via AUTHELIA_NOTIFIER_SMTP_USERNAME); password from the _FILE secret.
              settings.notifier = {
                smtp = {
                  address = "submission://smtp.gmail.com:587";
                  identifier = cfg.domain;
                  username = ''{{ env "AUTHELIA_NOTIFIER_SMTP_USERNAME" }}'';
                  sender = "Authelia <{{ env \"AUTHELIA_NOTIFIER_SMTP_USERNAME\" }}>";
                };
              };
              jwtSecretFile = cfg.secrets.authelia.jwtSecret;
              sessionSecretFile = cfg.secrets.authelia.sessionSecret;
              storageEncryptionKeyFile = cfg.secrets.authelia.storageEncryptionKey;
              oidc = {
                enable = true;
                hmacSecretFile = cfg.secrets.authelia.oidc.hmacSecret;
                jwksRsaKeyFile = cfg.secrets.authelia.oidc.jwksRsaKey;
              };
              # Authelia(-only) container env: feed the SMTP credentials to the
              # `template` config filters. Username comes from a sops file's
              # content; password via the _FILE secret mount (never inline).
              containers.authelia = {
                extraEnv.AUTHELIA_NOTIFIER_SMTP_USERNAME.fromFile = cfg.secrets.authelia.smtpUser;
                fileEnvMount.AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE = cfg.secrets.authelia.smtpPassword;
              };
            };

            lldap = {
              enable = true;
              # lldap only reads its config via the LLDAP_* env prefix, so NPS's
              # unprefixed FORCE_LDAP_USER_PASS_RESET=always is ignored. Put it in
              # the config file instead so the admin password is re-synced from the
              # secret file at every start (makes secret rotation take effect).
              # settings.force_ldap_user_pass_reset = "always"; # comment in if admin secret changes
              adminPasswordFile = cfg.secrets.lldap.adminPassword;
              jwtSecretFile = cfg.secrets.lldap.jwtSecret;
              keySeedFile = cfg.secrets.lldap.keySeed;
              # bootstrap.users.deer = {
              #   email = "no_reply@${cfg.domain}";
              #   password_file = cfg.secrets.lldap.deerPassword;
              #   groups = ["homepage_user" "paperless_user" "grafana_admin" "grafana_user"];
              # };
            };

            homepage = {
              enable = true;
              authSecretFile = cfg.secrets.homepage.authSecret;
              oidc = {
                enable = true;
                clientSecretFile = cfg.secrets.homepage.oidcClientSecret;
              };
            };

            paperless = {
              enable = true;
              enableTika = true;
              oidc.enable = true;
              oidc.clientSecretFile = cfg.secrets.paperless.oidcClientSecret;
              secretKeyFile = cfg.secrets.paperless.secretKey;
              db.passwordFile = cfg.secrets.paperless.dbPassword;
              adminProvisioning.email = "no_reply@${cfg.domain}";
              adminProvisioning.passwordFile = cfg.secrets.paperless.adminPassword;
            };

            monitoring = {
              enable = true;
              grafana.oidc = {
                enable = true;
                clientSecretFile = cfg.secrets.monitoring.grafanaOidcClientSecret;
              };
            };

            pinepods = {
              enable = true;
              adminProvisioning = {
                enable = true;
                email = "no_reply@${cfg.domain}";
                passwordFile = cfg.secrets.pinepods.adminPassword;
              };
              db.passwordFile = cfg.secrets.pinepods.dbPassword;
              oidc = {
                enable = true;
                clientSecretFile = cfg.secrets.pinepods.oidcClientSecret;
              };
            };
          };
        };

        # Make all user-facing services publicly reachable through Traefik.
        # Required anyway: the `private` middleware bypasses 127.0.0.1, which
        # would block every request coming from the Cloudflare Tunnel.
        services.podman.containers =
          (lib.genAttrs publicContainers (n: {
            expose = true;
          }))
          // {
            # Both containers read the bouncer key at start (via
            # create-extra-files), so order them after the generator.
            crowdsec.dependsOn = ["crowdsec-bouncer-key.service"];
            traefik.dependsOn = ["crowdsec-bouncer-key.service"];
            # lldap is tailnet-only: replace the default `private` middleware
            # (RFC1918-only) with one that also allows Tailscale CGNAT.
            lldap = {
              traefik.middleware = {
                private.enable = mkForce false;
                "ipwhitelist-tailnet".enable = true;
              };
            };
          };

        # Generate the Crowdsec LAPI key for the Traefik bouncer before the
        # affected containers launch. The key is created exactly once (persisted
        # next to the LAPI database, which registers the bouncer only on first
        # init) and read by both the crowdsec and traefik containers.
        systemd.user.services."crowdsec-bouncer-key" = {
          Unit = {
            Description = "Generate Crowdsec LAPI bouncer key for Traefik";
            # Ordering alone is not enough; the generators append Requires= for
            # both containers so they actually wait for us.
            Before = ["podman-crowdsec.service" "podman-traefik.service"];
          };
          Service = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStart = "${pkgs.bash}/bin/bash ${pkgs.writeScript "crowdsec-bouncer-key" ''
              set -euo pipefail
              # Idempotent: crowdsec registers the bouncer in LAPI only on first
              # init, so the key must never change afterwards.
              if [ ! -f ${cfg.crowdsec.bouncerKeyFile} ]; then
                mkdir -p "$(dirname ${cfg.crowdsec.bouncerKeyFile})"
                ${pkgs.openssl}/bin/openssl rand -hex 32 > ${cfg.crowdsec.bouncerKeyFile}
                chmod 600 ${cfg.crowdsec.bouncerKeyFile}
              fi
            ''}";
          };
          # Pulled in with the rest of the session; the Requires= links from the
          # containers guarantee ordering.
          Install.WantedBy = ["default.target"];
        };

        # Bind Traefik to loopback instead of :80/:443 (nginx still owns those).
        # Socket activation passes the FDs into the container, so only the host
        # socket units need to change; the entryPoint `address` fields keep the
        # default :80/:443 so generated redirects still point at the public host.
        systemd.user.sockets = {
          "podman-traefik-80" = {
            Socket.ListenStream = mkForce "127.0.0.1:8080";
            Socket.ListenDatagram = mkForce "127.0.0.1:8080";
          };
          "podman-traefik-443" = {
            Socket.ListenStream = mkForce "127.0.0.1:8443";
            Socket.ListenDatagram = mkForce "127.0.0.1:8443";
          };
        };
      };
    }

    # Cloudflare Tunnel pairing into the existing public reverse proxy
    (mkIf cfg.cloudflared.enable {
      systemd.services.cloudflared = {
        description = "Cloudflare Tunnel";
        wantedBy = ["multi-user.target"];
        after = ["network-online.target"];
        wants = ["network-online.target"];
        serviceConfig = {
          Type = "simple";
          Restart = "on-failure";
          RestartSec = "5s";
          EnvironmentFile = cfg.cloudflared.tokenFile;
          ExecStart = "${pkgs.cloudflared}/bin/cloudflared --no-autoupdate tunnel run";
        };
      };
    })
  ]);
}