{ config, inputs, lib, pkgs, ... }:
let
  cfg = config.my.nps;
  inherit (lib) mkIf mkOption mkEnableOption mkForce mkDefault mkMerge types literalExpression;

  publicContainers = [
    "traefik"
    "homepage"
    "authelia"
    "lldap"
    "paperless"
    "grafana"
    "alloy"
    "prometheus"
  ];
in {
  options.my.nps = {
    enable = mkEnableOption "Nix Podman Stacks (reverse proxy, auth, monitoring)";

    userName = mkOption {
      type = types.str;
      default = "deer";
      description = "User that runs the rootless Podman containers.";
    };

    hostIP4Address = mkOption {
      type = types.str;
      description = "IPv4 address used for explicit bindings (only relevant when Traefik is disabled).";
    };

    domain = mkOption {
      type = types.str;
      description = ''
        Base domain handled by Traefik. Build-time value.
        Read from a private, untracked file (e.g. /etc/nixos/nps-domain) by the
        host so the literal domain never lives in this repo.
      '';
    };

    acmeEmail = mkOption {
      type = types.str;
      description = "Let's Encrypt registration email. Cannot be loaded from a file (Traefik static config sources are mutually exclusive).";
    };

    defaultTz = mkOption {
      type = types.str;
      default = "America/Chicago";
    };

    storageBaseDir = mkOption {
      type = types.path;
      default = "/home/deer/stacks";
    };

    externalStorageBaseDir = mkOption {
      type = types.path;
      default = "/srv/array0/services";
    };

    mediaStorageBaseDir = mkOption {
      type = types.path;
      default = "/srv/array0/media";
    };

    cloudflared = {
      enable = mkEnableOption "systemd service running Cloudflare Tunnel with a token from sops";
      tokenFile = mkOption {
        type = types.path;
        description = "Dotenv file containing TUNNEL_TOKEN=... (for EnvironmentFile)";
      };
    };

    crowdsec = {
      bouncerKeyFile = mkOption {
        type = types.str;
        default = "${cfg.storageBaseDir}/crowdsec/bouncer-key";
        description = ''
          Persistent path to the Crowdsec LAPI key for the Traefik bouncer.
          The key is generated by a systemd oneshot on first activation and must
          live next to the Crowdsec LAPI database (Crowdsec registers the bouncer
          only once).
        '';
      };
    };

    secrets = {
      traefik = {
        cfDnsApiToken = mkOption {type = types.path;};
      };
      authelia = {
        jwtSecret = mkOption {type = types.path;};
        sessionSecret = mkOption {type = types.path;};
        storageEncryptionKey = mkOption {type = types.path;};
        oidc = {
          hmacSecret = mkOption {type = types.path;};
          jwksRsaKey = mkOption {type = types.path;};
        };
      };
      lldap = {
        adminPassword = mkOption {type = types.path;};
        jwtSecret = mkOption {type = types.path;};
        keySeed = mkOption {type = types.path;};
        # deerPassword = mkOption {type = types.path;};
      };
      homepage = {
        authSecret = mkOption {type = types.path;};
        oidcClientSecret = mkOption {type = types.path;};
      };
      paperless = {
        oidcClientSecret = mkOption {type = types.path;};
        secretKey = mkOption {type = types.path;};
        dbPassword = mkOption {type = types.path;};
        adminPassword = mkOption {type = types.path;};
      };
      monitoring = {
        grafanaOidcClientSecret = mkOption {type = types.path;};
      };
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      # NixOS-level prerequisites for rootless Podman
      boot.kernel.sysctl."net.ipv4.ip_unprivileged_port_start" = 0;
      virtualisation.podman.enable = mkDefault true;
      users.users.${cfg.userName}.linger = true;

      # Forward our flake inputs into the home-manager user submodule so that
      # `inputs.nix-podman-stacks.homeModules.nps` resolves there.
      home-manager.extraSpecialArgs.inputs = inputs;
    }

    # Wire the NPS home-manager module into the container user
    {
      home-manager.users.${cfg.userName} = {
        imports = [ inputs.nix-podman-stacks.homeModules.nps ];

        nps = {
          defaultTz = cfg.defaultTz;
          storageBaseDir = cfg.storageBaseDir;
          externalStorageBaseDir = cfg.externalStorageBaseDir;
          mediaStorageBaseDir = cfg.mediaStorageBaseDir;
          hostIP4Address = cfg.hostIP4Address;

          stacks = {
            docker-socket-proxy.enable = true;

            crowdsec = {
              enable = true;
            };

            traefik = {
              enable = true;
              domain = cfg.domain;
              # Cloudflare DNS challenge (merged into the traefik container's env)
              extraEnv.CF_DNS_API_TOKEN.fromFile = cfg.secrets.traefik.cfDnsApiToken;
              # Geoblock everything except the chosen country
              geoblock = {
                enable = true;
                allowedCountries = ["US"];
              };
              crowdsec = {
                enableLogCollection = true;
                middleware = {
                  enable = true;
                  bouncerKeyFile = cfg.crowdsec.bouncerKeyFile;
                };
              };
              # Custom LE email (build-time value, cannot come from a file)
              staticConfig.certificatesResolvers.letsencrypt.acme.email = mkForce cfg.acmeEmail;
              dynamicConfig.tls.options.default.sniStrict = mkForce false;
              # Traffic arrives at Traefik from cloudflared's loopback origin
              # (127.0.0.1:8443), so the bouncer must trust that hop to read the
              # real client IP from X-Forwarded-For.
              dynamicConfig.http.middlewares.crowdsec.plugin.bouncer.clientTrustedIPs =
                mkForce [
                  "127.0.0.1/32"
                  "::1/128"
                  "10.0.0.0/8"
                  "172.16.0.0/12"
                  "192.168.0.0/16"
                ];
            };

            authelia = {
              enable = true;
              jwtSecretFile = cfg.secrets.authelia.jwtSecret;
              sessionSecretFile = cfg.secrets.authelia.sessionSecret;
              storageEncryptionKeyFile = cfg.secrets.authelia.storageEncryptionKey;
              oidc = {
                enable = true;
                hmacSecretFile = cfg.secrets.authelia.oidc.hmacSecret;
                jwksRsaKeyFile = cfg.secrets.authelia.oidc.jwksRsaKey;
              };
            };

            lldap = {
              enable = true;
              adminPasswordFile = cfg.secrets.lldap.adminPassword;
              jwtSecretFile = cfg.secrets.lldap.jwtSecret;
              keySeedFile = cfg.secrets.lldap.keySeed;
              # bootstrap.users.deer = {
              #   email = "deer@${cfg.domain}";
              #   password_file = cfg.secrets.lldap.deerPassword;
              #   groups = ["homepage_user" "paperless_user" "grafana_admin" "grafana_user"];
              # };
            };

            homepage = {
              enable = true;
              authSecretFile = cfg.secrets.homepage.authSecret;
              oidc = {
                enable = true;
                clientSecretFile = cfg.secrets.homepage.oidcClientSecret;
              };
            };

            paperless = {
              enable = true;
              enableTika = true;
              oidc.enable = true;
              oidc.clientSecretFile = cfg.secrets.paperless.oidcClientSecret;
              secretKeyFile = cfg.secrets.paperless.secretKey;
              db.passwordFile = cfg.secrets.paperless.dbPassword;
              adminProvisioning.email = "deer@${cfg.domain}";
              adminProvisioning.passwordFile = cfg.secrets.paperless.adminPassword;
            };

            monitoring = {
              enable = true;
              grafana.oidc = {
                enable = true;
                clientSecretFile = cfg.secrets.monitoring.grafanaOidcClientSecret;
              };
            };
          };
        };

        # Make all user-facing services publicly reachable through Traefik.
        # Required anyway: the `private` middleware bypasses 127.0.0.1, which
        # would block every request coming from the Cloudflare Tunnel.
        services.podman.containers =
          (lib.genAttrs publicContainers (n: {
            expose = true;
          }))
          // {
            # Both containers read the bouncer key at start (via
            # create-extra-files), so order them after the generator.
            crowdsec.dependsOn = ["crowdsec-bouncer-key.service"];
            traefik.dependsOn = ["crowdsec-bouncer-key.service"];
          };

        # Generate the Crowdsec LAPI key for the Traefik bouncer before the
        # affected containers launch. The key is created exactly once (persisted
        # next to the LAPI database, which registers the bouncer only on first
        # init) and read by both the crowdsec and traefik containers.
        systemd.user.services."crowdsec-bouncer-key" = {
          Unit = {
            Description = "Generate Crowdsec LAPI bouncer key for Traefik";
            # Ordering alone is not enough; the generators append Requires= for
            # both containers so they actually wait for us.
            Before = ["podman-crowdsec.service" "podman-traefik.service"];
          };
          Service = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStart = "${pkgs.bash}/bin/bash ${pkgs.writeScript "crowdsec-bouncer-key" ''
              set -euo pipefail
              # Idempotent: crowdsec registers the bouncer in LAPI only on first
              # init, so the key must never change afterwards.
              if [ ! -f ${cfg.crowdsec.bouncerKeyFile} ]; then
                mkdir -p "$(dirname ${cfg.crowdsec.bouncerKeyFile})"
                ${pkgs.openssl}/bin/openssl rand -hex 32 > ${cfg.crowdsec.bouncerKeyFile}
                chmod 600 ${cfg.crowdsec.bouncerKeyFile}
              fi
            ''}";
          };
          # Pulled in with the rest of the session; the Requires= links from the
          # containers guarantee ordering.
          Install.WantedBy = ["default.target"];
        };

        # Bind Traefik to loopback instead of :80/:443 (nginx still owns those).
        # Socket activation passes the FDs into the container, so only the host
        # socket units need to change; the entryPoint `address` fields keep the
        # default :80/:443 so generated redirects still point at the public host.
        systemd.user.sockets = {
          "podman-traefik-80" = {
            Socket.ListenStream = mkForce "127.0.0.1:8080";
            Socket.ListenDatagram = mkForce "127.0.0.1:8080";
          };
          "podman-traefik-443" = {
            Socket.ListenStream = mkForce "127.0.0.1:8443";
            Socket.ListenDatagram = mkForce "127.0.0.1:8443";
          };
        };
      };
    }

    # Cloudflare Tunnel pairing into the existing public reverse proxy
    (mkIf cfg.cloudflared.enable {
      systemd.services.cloudflared = {
        description = "Cloudflare Tunnel";
        wantedBy = ["multi-user.target"];
        after = ["network-online.target"];
        wants = ["network-online.target"];
        serviceConfig = {
          Type = "simple";
          Restart = "on-failure";
          RestartSec = "5s";
          EnvironmentFile = cfg.cloudflared.tokenFile;
          ExecStart = "${pkgs.cloudflared}/bin/cloudflared --no-autoupdate tunnel run";
        };
      };
    })
  ]);
}